// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyhsodozcijlfkmveabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55aHNvZG96Y2lqbGZrbXZlYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjM0ODQsImV4cCI6MjA3MDI5OTQ4NH0.s7lbiFh-lChmxE6qVbKMjYy_XmjBpqbMzdml0yT225I"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});